/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as PosIndexImport } from './routes/pos/index'
import { Route as LayoutProtectedImport } from './routes/_layout/_protected'
import { Route as LayoutEntranceIndexImport } from './routes/_layout/entrance/index'
import { Route as LayoutProtectedLayoutImport } from './routes/_layout/_protected/_layout'
import { Route as LayoutProtectedLayoutTravelLogIndexImport } from './routes/_layout/_protected/_layout/travelLog/index'
import { Route as LayoutProtectedLayoutProfileIndexImport } from './routes/_layout/_protected/_layout/profile/index'
import { Route as LayoutProtectedLayoutAccountIndexImport } from './routes/_layout/_protected/_layout/account/index'
import { Route as LayoutProtectedLayoutQuizTravelIdImport } from './routes/_layout/_protected/_layout/quiz/$travelId'
import { Route as LayoutProtectedLayoutAccountSettleIndexImport } from './routes/_layout/_protected/_layout/account/settle/index'
import { Route as LayoutProtectedLayoutQuizInviteTravelIdImport } from './routes/_layout/_protected/_layout/quiz/invite/$travelId'
import { Route as LayoutProtectedLayoutAccountResultByReceiptLayoutImport } from './routes/_layout/_protected/_layout/account/resultByReceipt/_layout'
import { Route as LayoutProtectedLayoutAccountDetailLayoutImport } from './routes/_layout/_protected/_layout/account/detail/_layout'
import { Route as LayoutProtectedLayoutAccountResultByReceiptLayoutTransactionIdImport } from './routes/_layout/_protected/_layout/account/resultByReceipt/_layout/$transactionId'
import { Route as LayoutProtectedLayoutAccountDetailLayoutTransactionIdImport } from './routes/_layout/_protected/_layout/account/detail/_layout/$transactionId'

// Create Virtual Routes

const LayoutProtectedLayoutAccountResultByReceiptImport = createFileRoute(
  '/_layout/_protected/_layout/account/resultByReceipt',
)()
const LayoutProtectedLayoutAccountDetailImport = createFileRoute(
  '/_layout/_protected/_layout/account/detail',
)()
const LayoutProtectedLayoutHomeIndexLazyImport = createFileRoute(
  '/_layout/_protected/_layout/_Home/',
)()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const PosIndexRoute = PosIndexImport.update({
  path: '/pos/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutProtectedRoute = LayoutProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutEntranceIndexRoute = LayoutEntranceIndexImport.update({
  path: '/entrance/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProtectedLayoutRoute = LayoutProtectedLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => LayoutProtectedRoute,
} as any)

const LayoutProtectedLayoutAccountResultByReceiptRoute =
  LayoutProtectedLayoutAccountResultByReceiptImport.update({
    path: '/account/resultByReceipt',
    getParentRoute: () => LayoutProtectedLayoutRoute,
  } as any)

const LayoutProtectedLayoutAccountDetailRoute =
  LayoutProtectedLayoutAccountDetailImport.update({
    path: '/account/detail',
    getParentRoute: () => LayoutProtectedLayoutRoute,
  } as any)

const LayoutProtectedLayoutHomeIndexLazyRoute =
  LayoutProtectedLayoutHomeIndexLazyImport.update({
    path: '/',
    getParentRoute: () => LayoutProtectedLayoutRoute,
  } as any).lazy(() =>
    import('./routes/_layout/_protected/_layout/_Home/index.lazy').then(
      (d) => d.Route,
    ),
  )

const LayoutProtectedLayoutTravelLogIndexRoute =
  LayoutProtectedLayoutTravelLogIndexImport.update({
    path: '/travelLog/',
    getParentRoute: () => LayoutProtectedLayoutRoute,
  } as any)

const LayoutProtectedLayoutProfileIndexRoute =
  LayoutProtectedLayoutProfileIndexImport.update({
    path: '/profile/',
    getParentRoute: () => LayoutProtectedLayoutRoute,
  } as any)

const LayoutProtectedLayoutAccountIndexRoute =
  LayoutProtectedLayoutAccountIndexImport.update({
    path: '/account/',
    getParentRoute: () => LayoutProtectedLayoutRoute,
  } as any)

const LayoutProtectedLayoutQuizTravelIdRoute =
  LayoutProtectedLayoutQuizTravelIdImport.update({
    path: '/quiz/$travelId',
    getParentRoute: () => LayoutProtectedLayoutRoute,
  } as any)

const LayoutProtectedLayoutAccountSettleIndexRoute =
  LayoutProtectedLayoutAccountSettleIndexImport.update({
    path: '/account/settle/',
    getParentRoute: () => LayoutProtectedLayoutRoute,
  } as any)

const LayoutProtectedLayoutQuizInviteTravelIdRoute =
  LayoutProtectedLayoutQuizInviteTravelIdImport.update({
    path: '/quiz/invite/$travelId',
    getParentRoute: () => LayoutProtectedLayoutRoute,
  } as any)

const LayoutProtectedLayoutAccountResultByReceiptLayoutRoute =
  LayoutProtectedLayoutAccountResultByReceiptLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedLayoutAccountResultByReceiptRoute,
  } as any)

const LayoutProtectedLayoutAccountDetailLayoutRoute =
  LayoutProtectedLayoutAccountDetailLayoutImport.update({
    id: '/_layout',
    getParentRoute: () => LayoutProtectedLayoutAccountDetailRoute,
  } as any)

const LayoutProtectedLayoutAccountResultByReceiptLayoutTransactionIdRoute =
  LayoutProtectedLayoutAccountResultByReceiptLayoutTransactionIdImport.update({
    path: '/$transactionId',
    getParentRoute: () =>
      LayoutProtectedLayoutAccountResultByReceiptLayoutRoute,
  } as any)

const LayoutProtectedLayoutAccountDetailLayoutTransactionIdRoute =
  LayoutProtectedLayoutAccountDetailLayoutTransactionIdImport.update({
    path: '/$transactionId',
    getParentRoute: () => LayoutProtectedLayoutAccountDetailLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_protected': {
      id: '/_layout/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutProtectedImport
      parentRoute: typeof LayoutImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosIndexImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_protected/_layout': {
      id: '/_layout/_protected/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutProtectedLayoutImport
      parentRoute: typeof LayoutProtectedImport
    }
    '/_layout/entrance/': {
      id: '/_layout/entrance/'
      path: '/entrance'
      fullPath: '/entrance'
      preLoaderRoute: typeof LayoutEntranceIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_protected/_layout/quiz/$travelId': {
      id: '/_layout/_protected/_layout/quiz/$travelId'
      path: '/quiz/$travelId'
      fullPath: '/quiz/$travelId'
      preLoaderRoute: typeof LayoutProtectedLayoutQuizTravelIdImport
      parentRoute: typeof LayoutProtectedLayoutImport
    }
    '/_layout/_protected/_layout/account/': {
      id: '/_layout/_protected/_layout/account/'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof LayoutProtectedLayoutAccountIndexImport
      parentRoute: typeof LayoutProtectedLayoutImport
    }
    '/_layout/_protected/_layout/profile/': {
      id: '/_layout/_protected/_layout/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutProtectedLayoutProfileIndexImport
      parentRoute: typeof LayoutProtectedLayoutImport
    }
    '/_layout/_protected/_layout/travelLog/': {
      id: '/_layout/_protected/_layout/travelLog/'
      path: '/travelLog'
      fullPath: '/travelLog'
      preLoaderRoute: typeof LayoutProtectedLayoutTravelLogIndexImport
      parentRoute: typeof LayoutProtectedLayoutImport
    }
    '/_layout/_protected/_layout/_Home/': {
      id: '/_layout/_protected/_layout/_Home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutProtectedLayoutHomeIndexLazyImport
      parentRoute: typeof LayoutProtectedLayoutImport
    }
    '/_layout/_protected/_layout/account/detail': {
      id: '/_layout/_protected/_layout/account/detail'
      path: '/account/detail'
      fullPath: '/account/detail'
      preLoaderRoute: typeof LayoutProtectedLayoutAccountDetailImport
      parentRoute: typeof LayoutProtectedLayoutImport
    }
    '/_layout/_protected/_layout/account/detail/_layout': {
      id: '/_layout/_protected/_layout/account/detail/_layout'
      path: '/account/detail'
      fullPath: '/account/detail'
      preLoaderRoute: typeof LayoutProtectedLayoutAccountDetailLayoutImport
      parentRoute: typeof LayoutProtectedLayoutAccountDetailRoute
    }
    '/_layout/_protected/_layout/account/resultByReceipt': {
      id: '/_layout/_protected/_layout/account/resultByReceipt'
      path: '/account/resultByReceipt'
      fullPath: '/account/resultByReceipt'
      preLoaderRoute: typeof LayoutProtectedLayoutAccountResultByReceiptImport
      parentRoute: typeof LayoutProtectedLayoutImport
    }
    '/_layout/_protected/_layout/account/resultByReceipt/_layout': {
      id: '/_layout/_protected/_layout/account/resultByReceipt/_layout'
      path: '/account/resultByReceipt'
      fullPath: '/account/resultByReceipt'
      preLoaderRoute: typeof LayoutProtectedLayoutAccountResultByReceiptLayoutImport
      parentRoute: typeof LayoutProtectedLayoutAccountResultByReceiptRoute
    }
    '/_layout/_protected/_layout/quiz/invite/$travelId': {
      id: '/_layout/_protected/_layout/quiz/invite/$travelId'
      path: '/quiz/invite/$travelId'
      fullPath: '/quiz/invite/$travelId'
      preLoaderRoute: typeof LayoutProtectedLayoutQuizInviteTravelIdImport
      parentRoute: typeof LayoutProtectedLayoutImport
    }
    '/_layout/_protected/_layout/account/settle/': {
      id: '/_layout/_protected/_layout/account/settle/'
      path: '/account/settle'
      fullPath: '/account/settle'
      preLoaderRoute: typeof LayoutProtectedLayoutAccountSettleIndexImport
      parentRoute: typeof LayoutProtectedLayoutImport
    }
    '/_layout/_protected/_layout/account/detail/_layout/$transactionId': {
      id: '/_layout/_protected/_layout/account/detail/_layout/$transactionId'
      path: '/$transactionId'
      fullPath: '/account/detail/$transactionId'
      preLoaderRoute: typeof LayoutProtectedLayoutAccountDetailLayoutTransactionIdImport
      parentRoute: typeof LayoutProtectedLayoutAccountDetailLayoutImport
    }
    '/_layout/_protected/_layout/account/resultByReceipt/_layout/$transactionId': {
      id: '/_layout/_protected/_layout/account/resultByReceipt/_layout/$transactionId'
      path: '/$transactionId'
      fullPath: '/account/resultByReceipt/$transactionId'
      preLoaderRoute: typeof LayoutProtectedLayoutAccountResultByReceiptLayoutTransactionIdImport
      parentRoute: typeof LayoutProtectedLayoutAccountResultByReceiptLayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutProtectedLayoutAccountDetailLayoutRouteChildren {
  LayoutProtectedLayoutAccountDetailLayoutTransactionIdRoute: typeof LayoutProtectedLayoutAccountDetailLayoutTransactionIdRoute
}

const LayoutProtectedLayoutAccountDetailLayoutRouteChildren: LayoutProtectedLayoutAccountDetailLayoutRouteChildren =
  {
    LayoutProtectedLayoutAccountDetailLayoutTransactionIdRoute:
      LayoutProtectedLayoutAccountDetailLayoutTransactionIdRoute,
  }

const LayoutProtectedLayoutAccountDetailLayoutRouteWithChildren =
  LayoutProtectedLayoutAccountDetailLayoutRoute._addFileChildren(
    LayoutProtectedLayoutAccountDetailLayoutRouteChildren,
  )

interface LayoutProtectedLayoutAccountDetailRouteChildren {
  LayoutProtectedLayoutAccountDetailLayoutRoute: typeof LayoutProtectedLayoutAccountDetailLayoutRouteWithChildren
}

const LayoutProtectedLayoutAccountDetailRouteChildren: LayoutProtectedLayoutAccountDetailRouteChildren =
  {
    LayoutProtectedLayoutAccountDetailLayoutRoute:
      LayoutProtectedLayoutAccountDetailLayoutRouteWithChildren,
  }

const LayoutProtectedLayoutAccountDetailRouteWithChildren =
  LayoutProtectedLayoutAccountDetailRoute._addFileChildren(
    LayoutProtectedLayoutAccountDetailRouteChildren,
  )

interface LayoutProtectedLayoutAccountResultByReceiptLayoutRouteChildren {
  LayoutProtectedLayoutAccountResultByReceiptLayoutTransactionIdRoute: typeof LayoutProtectedLayoutAccountResultByReceiptLayoutTransactionIdRoute
}

const LayoutProtectedLayoutAccountResultByReceiptLayoutRouteChildren: LayoutProtectedLayoutAccountResultByReceiptLayoutRouteChildren =
  {
    LayoutProtectedLayoutAccountResultByReceiptLayoutTransactionIdRoute:
      LayoutProtectedLayoutAccountResultByReceiptLayoutTransactionIdRoute,
  }

const LayoutProtectedLayoutAccountResultByReceiptLayoutRouteWithChildren =
  LayoutProtectedLayoutAccountResultByReceiptLayoutRoute._addFileChildren(
    LayoutProtectedLayoutAccountResultByReceiptLayoutRouteChildren,
  )

interface LayoutProtectedLayoutAccountResultByReceiptRouteChildren {
  LayoutProtectedLayoutAccountResultByReceiptLayoutRoute: typeof LayoutProtectedLayoutAccountResultByReceiptLayoutRouteWithChildren
}

const LayoutProtectedLayoutAccountResultByReceiptRouteChildren: LayoutProtectedLayoutAccountResultByReceiptRouteChildren =
  {
    LayoutProtectedLayoutAccountResultByReceiptLayoutRoute:
      LayoutProtectedLayoutAccountResultByReceiptLayoutRouteWithChildren,
  }

const LayoutProtectedLayoutAccountResultByReceiptRouteWithChildren =
  LayoutProtectedLayoutAccountResultByReceiptRoute._addFileChildren(
    LayoutProtectedLayoutAccountResultByReceiptRouteChildren,
  )

interface LayoutProtectedLayoutRouteChildren {
  LayoutProtectedLayoutQuizTravelIdRoute: typeof LayoutProtectedLayoutQuizTravelIdRoute
  LayoutProtectedLayoutAccountIndexRoute: typeof LayoutProtectedLayoutAccountIndexRoute
  LayoutProtectedLayoutProfileIndexRoute: typeof LayoutProtectedLayoutProfileIndexRoute
  LayoutProtectedLayoutTravelLogIndexRoute: typeof LayoutProtectedLayoutTravelLogIndexRoute
  LayoutProtectedLayoutHomeIndexLazyRoute: typeof LayoutProtectedLayoutHomeIndexLazyRoute
  LayoutProtectedLayoutAccountDetailRoute: typeof LayoutProtectedLayoutAccountDetailRouteWithChildren
  LayoutProtectedLayoutAccountResultByReceiptRoute: typeof LayoutProtectedLayoutAccountResultByReceiptRouteWithChildren
  LayoutProtectedLayoutQuizInviteTravelIdRoute: typeof LayoutProtectedLayoutQuizInviteTravelIdRoute
  LayoutProtectedLayoutAccountSettleIndexRoute: typeof LayoutProtectedLayoutAccountSettleIndexRoute
}

const LayoutProtectedLayoutRouteChildren: LayoutProtectedLayoutRouteChildren = {
  LayoutProtectedLayoutQuizTravelIdRoute:
    LayoutProtectedLayoutQuizTravelIdRoute,
  LayoutProtectedLayoutAccountIndexRoute:
    LayoutProtectedLayoutAccountIndexRoute,
  LayoutProtectedLayoutProfileIndexRoute:
    LayoutProtectedLayoutProfileIndexRoute,
  LayoutProtectedLayoutTravelLogIndexRoute:
    LayoutProtectedLayoutTravelLogIndexRoute,
  LayoutProtectedLayoutHomeIndexLazyRoute:
    LayoutProtectedLayoutHomeIndexLazyRoute,
  LayoutProtectedLayoutAccountDetailRoute:
    LayoutProtectedLayoutAccountDetailRouteWithChildren,
  LayoutProtectedLayoutAccountResultByReceiptRoute:
    LayoutProtectedLayoutAccountResultByReceiptRouteWithChildren,
  LayoutProtectedLayoutQuizInviteTravelIdRoute:
    LayoutProtectedLayoutQuizInviteTravelIdRoute,
  LayoutProtectedLayoutAccountSettleIndexRoute:
    LayoutProtectedLayoutAccountSettleIndexRoute,
}

const LayoutProtectedLayoutRouteWithChildren =
  LayoutProtectedLayoutRoute._addFileChildren(
    LayoutProtectedLayoutRouteChildren,
  )

interface LayoutProtectedRouteChildren {
  LayoutProtectedLayoutRoute: typeof LayoutProtectedLayoutRouteWithChildren
}

const LayoutProtectedRouteChildren: LayoutProtectedRouteChildren = {
  LayoutProtectedLayoutRoute: LayoutProtectedLayoutRouteWithChildren,
}

const LayoutProtectedRouteWithChildren = LayoutProtectedRoute._addFileChildren(
  LayoutProtectedRouteChildren,
)

interface LayoutRouteChildren {
  LayoutProtectedRoute: typeof LayoutProtectedRouteWithChildren
  LayoutEntranceIndexRoute: typeof LayoutEntranceIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutProtectedRoute: LayoutProtectedRouteWithChildren,
  LayoutEntranceIndexRoute: LayoutEntranceIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutProtectedLayoutRouteWithChildren
  '/pos': typeof PosIndexRoute
  '/entrance': typeof LayoutEntranceIndexRoute
  '/quiz/$travelId': typeof LayoutProtectedLayoutQuizTravelIdRoute
  '/account': typeof LayoutProtectedLayoutAccountIndexRoute
  '/profile': typeof LayoutProtectedLayoutProfileIndexRoute
  '/travelLog': typeof LayoutProtectedLayoutTravelLogIndexRoute
  '/': typeof LayoutProtectedLayoutHomeIndexLazyRoute
  '/account/detail': typeof LayoutProtectedLayoutAccountDetailLayoutRouteWithChildren
  '/account/resultByReceipt': typeof LayoutProtectedLayoutAccountResultByReceiptLayoutRouteWithChildren
  '/quiz/invite/$travelId': typeof LayoutProtectedLayoutQuizInviteTravelIdRoute
  '/account/settle': typeof LayoutProtectedLayoutAccountSettleIndexRoute
  '/account/detail/$transactionId': typeof LayoutProtectedLayoutAccountDetailLayoutTransactionIdRoute
  '/account/resultByReceipt/$transactionId': typeof LayoutProtectedLayoutAccountResultByReceiptLayoutTransactionIdRoute
}

export interface FileRoutesByTo {
  '': typeof LayoutProtectedRouteWithChildren
  '/pos': typeof PosIndexRoute
  '/entrance': typeof LayoutEntranceIndexRoute
  '/quiz/$travelId': typeof LayoutProtectedLayoutQuizTravelIdRoute
  '/account': typeof LayoutProtectedLayoutAccountIndexRoute
  '/profile': typeof LayoutProtectedLayoutProfileIndexRoute
  '/travelLog': typeof LayoutProtectedLayoutTravelLogIndexRoute
  '/': typeof LayoutProtectedLayoutHomeIndexLazyRoute
  '/account/detail': typeof LayoutProtectedLayoutAccountDetailLayoutRouteWithChildren
  '/account/resultByReceipt': typeof LayoutProtectedLayoutAccountResultByReceiptLayoutRouteWithChildren
  '/quiz/invite/$travelId': typeof LayoutProtectedLayoutQuizInviteTravelIdRoute
  '/account/settle': typeof LayoutProtectedLayoutAccountSettleIndexRoute
  '/account/detail/$transactionId': typeof LayoutProtectedLayoutAccountDetailLayoutTransactionIdRoute
  '/account/resultByReceipt/$transactionId': typeof LayoutProtectedLayoutAccountResultByReceiptLayoutTransactionIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_protected': typeof LayoutProtectedRouteWithChildren
  '/pos/': typeof PosIndexRoute
  '/_layout/_protected/_layout': typeof LayoutProtectedLayoutRouteWithChildren
  '/_layout/entrance/': typeof LayoutEntranceIndexRoute
  '/_layout/_protected/_layout/quiz/$travelId': typeof LayoutProtectedLayoutQuizTravelIdRoute
  '/_layout/_protected/_layout/account/': typeof LayoutProtectedLayoutAccountIndexRoute
  '/_layout/_protected/_layout/profile/': typeof LayoutProtectedLayoutProfileIndexRoute
  '/_layout/_protected/_layout/travelLog/': typeof LayoutProtectedLayoutTravelLogIndexRoute
  '/_layout/_protected/_layout/_Home/': typeof LayoutProtectedLayoutHomeIndexLazyRoute
  '/_layout/_protected/_layout/account/detail': typeof LayoutProtectedLayoutAccountDetailRouteWithChildren
  '/_layout/_protected/_layout/account/detail/_layout': typeof LayoutProtectedLayoutAccountDetailLayoutRouteWithChildren
  '/_layout/_protected/_layout/account/resultByReceipt': typeof LayoutProtectedLayoutAccountResultByReceiptRouteWithChildren
  '/_layout/_protected/_layout/account/resultByReceipt/_layout': typeof LayoutProtectedLayoutAccountResultByReceiptLayoutRouteWithChildren
  '/_layout/_protected/_layout/quiz/invite/$travelId': typeof LayoutProtectedLayoutQuizInviteTravelIdRoute
  '/_layout/_protected/_layout/account/settle/': typeof LayoutProtectedLayoutAccountSettleIndexRoute
  '/_layout/_protected/_layout/account/detail/_layout/$transactionId': typeof LayoutProtectedLayoutAccountDetailLayoutTransactionIdRoute
  '/_layout/_protected/_layout/account/resultByReceipt/_layout/$transactionId': typeof LayoutProtectedLayoutAccountResultByReceiptLayoutTransactionIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/pos'
    | '/entrance'
    | '/quiz/$travelId'
    | '/account'
    | '/profile'
    | '/travelLog'
    | '/'
    | '/account/detail'
    | '/account/resultByReceipt'
    | '/quiz/invite/$travelId'
    | '/account/settle'
    | '/account/detail/$transactionId'
    | '/account/resultByReceipt/$transactionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/pos'
    | '/entrance'
    | '/quiz/$travelId'
    | '/account'
    | '/profile'
    | '/travelLog'
    | '/'
    | '/account/detail'
    | '/account/resultByReceipt'
    | '/quiz/invite/$travelId'
    | '/account/settle'
    | '/account/detail/$transactionId'
    | '/account/resultByReceipt/$transactionId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_protected'
    | '/pos/'
    | '/_layout/_protected/_layout'
    | '/_layout/entrance/'
    | '/_layout/_protected/_layout/quiz/$travelId'
    | '/_layout/_protected/_layout/account/'
    | '/_layout/_protected/_layout/profile/'
    | '/_layout/_protected/_layout/travelLog/'
    | '/_layout/_protected/_layout/_Home/'
    | '/_layout/_protected/_layout/account/detail'
    | '/_layout/_protected/_layout/account/detail/_layout'
    | '/_layout/_protected/_layout/account/resultByReceipt'
    | '/_layout/_protected/_layout/account/resultByReceipt/_layout'
    | '/_layout/_protected/_layout/quiz/invite/$travelId'
    | '/_layout/_protected/_layout/account/settle/'
    | '/_layout/_protected/_layout/account/detail/_layout/$transactionId'
    | '/_layout/_protected/_layout/account/resultByReceipt/_layout/$transactionId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  PosIndexRoute: typeof PosIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  PosIndexRoute: PosIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/pos/"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_protected",
        "/_layout/entrance/"
      ]
    },
    "/_layout/_protected": {
      "filePath": "_layout/_protected.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_protected/_layout"
      ]
    },
    "/pos/": {
      "filePath": "pos/index.tsx"
    },
    "/_layout/_protected/_layout": {
      "filePath": "_layout/_protected/_layout.tsx",
      "parent": "/_layout/_protected",
      "children": [
        "/_layout/_protected/_layout/quiz/$travelId",
        "/_layout/_protected/_layout/account/",
        "/_layout/_protected/_layout/profile/",
        "/_layout/_protected/_layout/travelLog/",
        "/_layout/_protected/_layout/_Home/",
        "/_layout/_protected/_layout/account/detail",
        "/_layout/_protected/_layout/account/resultByReceipt",
        "/_layout/_protected/_layout/quiz/invite/$travelId",
        "/_layout/_protected/_layout/account/settle/"
      ]
    },
    "/_layout/entrance/": {
      "filePath": "_layout/entrance/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/_protected/_layout/quiz/$travelId": {
      "filePath": "_layout/_protected/_layout/quiz/$travelId.tsx",
      "parent": "/_layout/_protected/_layout"
    },
    "/_layout/_protected/_layout/account/": {
      "filePath": "_layout/_protected/_layout/account/index.tsx",
      "parent": "/_layout/_protected/_layout"
    },
    "/_layout/_protected/_layout/profile/": {
      "filePath": "_layout/_protected/_layout/profile/index.tsx",
      "parent": "/_layout/_protected/_layout"
    },
    "/_layout/_protected/_layout/travelLog/": {
      "filePath": "_layout/_protected/_layout/travelLog/index.tsx",
      "parent": "/_layout/_protected/_layout"
    },
    "/_layout/_protected/_layout/_Home/": {
      "filePath": "_layout/_protected/_layout/_Home/index.lazy.tsx",
      "parent": "/_layout/_protected/_layout"
    },
    "/_layout/_protected/_layout/account/detail": {
      "filePath": "_layout/_protected/_layout/account/detail",
      "parent": "/_layout/_protected/_layout",
      "children": [
        "/_layout/_protected/_layout/account/detail/_layout"
      ]
    },
    "/_layout/_protected/_layout/account/detail/_layout": {
      "filePath": "_layout/_protected/_layout/account/detail/_layout.tsx",
      "parent": "/_layout/_protected/_layout/account/detail",
      "children": [
        "/_layout/_protected/_layout/account/detail/_layout/$transactionId"
      ]
    },
    "/_layout/_protected/_layout/account/resultByReceipt": {
      "filePath": "_layout/_protected/_layout/account/resultByReceipt",
      "parent": "/_layout/_protected/_layout",
      "children": [
        "/_layout/_protected/_layout/account/resultByReceipt/_layout"
      ]
    },
    "/_layout/_protected/_layout/account/resultByReceipt/_layout": {
      "filePath": "_layout/_protected/_layout/account/resultByReceipt/_layout.tsx",
      "parent": "/_layout/_protected/_layout/account/resultByReceipt",
      "children": [
        "/_layout/_protected/_layout/account/resultByReceipt/_layout/$transactionId"
      ]
    },
    "/_layout/_protected/_layout/quiz/invite/$travelId": {
      "filePath": "_layout/_protected/_layout/quiz/invite/$travelId.tsx",
      "parent": "/_layout/_protected/_layout"
    },
    "/_layout/_protected/_layout/account/settle/": {
      "filePath": "_layout/_protected/_layout/account/settle/index.tsx",
      "parent": "/_layout/_protected/_layout"
    },
    "/_layout/_protected/_layout/account/detail/_layout/$transactionId": {
      "filePath": "_layout/_protected/_layout/account/detail/_layout/$transactionId.tsx",
      "parent": "/_layout/_protected/_layout/account/detail/_layout"
    },
    "/_layout/_protected/_layout/account/resultByReceipt/_layout/$transactionId": {
      "filePath": "_layout/_protected/_layout/account/resultByReceipt/_layout/$transactionId.tsx",
      "parent": "/_layout/_protected/_layout/account/resultByReceipt/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
