/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GroupAccountImport } from './routes/groupAccount'
import { Route as AboutImport } from './routes/About'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const GroupAccountRoute = GroupAccountImport.update({
  path: '/groupAccount',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  path: '/About',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/About': {
      id: '/About'
      path: '/About'
      fullPath: '/About'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/groupAccount': {
      id: '/groupAccount'
      path: '/groupAccount'
      fullPath: '/groupAccount'
      preLoaderRoute: typeof GroupAccountImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/About': typeof AboutRoute
  '/groupAccount': typeof GroupAccountRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/About': typeof AboutRoute
  '/groupAccount': typeof GroupAccountRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/About': typeof AboutRoute
  '/groupAccount': typeof GroupAccountRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/About' | '/groupAccount'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/About' | '/groupAccount'
  id: '__root__' | '/' | '/About' | '/groupAccount'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutRoute: typeof AboutRoute
  GroupAccountRoute: typeof GroupAccountRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutRoute: AboutRoute,
  GroupAccountRoute: GroupAccountRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/About",
        "/groupAccount"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/About": {
      "filePath": "About.tsx"
    },
    "/groupAccount": {
      "filePath": "groupAccount.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
