"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.balanceStyle = exports.notDepositStyle = exports.depositStyle = exports.downContainerStyle = exports.carouselStyle = exports.locationStyle = exports.timeStyle = exports.textContainerStyle = exports.upContainerStyle = exports.layoutStyle = void 0;
var react_1 = require("@emotion/react");
var colors_1 = require("@/styles/colors");
exports.layoutStyle = (0, react_1.css)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    width:330px;\n    height: 115px;\n    border-top: solid 1px ", ";\n    padding: 20px 20px;\n    display: flex;\n    flex-direction: column;\n    gap: 20px;\n\n    text-decoration: none; \n    color: inherit; \n    &:hover {\n        text-decoration: none; \n        color: inherit; \n    }\n"], ["\n    width:330px;\n    height: 115px;\n    border-top: solid 1px ", ";\n    padding: 20px 20px;\n    display: flex;\n    flex-direction: column;\n    gap: 20px;\n\n    text-decoration: none; \n    color: inherit; \n    &:hover {\n        text-decoration: none; \n        color: inherit; \n    }\n"])), colors_1.colors.lightGray);
exports.upContainerStyle = (0, react_1.css)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    display: flex;\n    justify-content: space-between;\n    width: 100%;\n    flex-grow: 1;\n"], ["\n    display: flex;\n    justify-content: space-between;\n    width: 100%;\n    flex-grow: 1;\n"])));
exports.textContainerStyle = (0, react_1.css)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    width: 200px;\n    display : flex;\n    flex-direction: column;\n    gap: 15px;\n"], ["\n    width: 200px;\n    display : flex;\n    flex-direction: column;\n    gap: 15px;\n"])));
exports.timeStyle = (0, react_1.css)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    font-family: 'regular';\n    font-size: 12px;\n"], ["\n    font-family: 'regular';\n    font-size: 12px;\n"])));
exports.locationStyle = (0, react_1.css)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n    padding-right: 15px;\n    font-family: 'semibold';\n    font-size: 20px;\n    overflow: hidden;\n    text-overflow: ellipsis;\n    white-space: nowrap;\n"], ["\n    padding-right: 15px;\n    font-family: 'semibold';\n    font-size: 20px;\n    overflow: hidden;\n    text-overflow: ellipsis;\n    white-space: nowrap;\n"])));
exports.carouselStyle = (0, react_1.css)(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n    display:flex;\n    width: 150px;\n    justify-content: flex-start;\n    flex-direction: row;\n    gap: 5px;\n    padding: 1px 0;\n\n    overflow-x: auto;\n\n    &::-webkit-scrollbar {\n    display: none;\n    }\n\n"], ["\n    display:flex;\n    width: 150px;\n    justify-content: flex-start;\n    flex-direction: row;\n    gap: 5px;\n    padding: 1px 0;\n\n    overflow-x: auto;\n\n    &::-webkit-scrollbar {\n    display: none;\n    }\n\n"])));
exports.downContainerStyle = (0, react_1.css)(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n    display : flex;\n    flex-direction: column;\n    gap: 15px;\n    flex-grow: 1;\n    \n"], ["\n    display : flex;\n    flex-direction: column;\n    gap: 15px;\n    flex-grow: 1;\n    \n"])));
exports.depositStyle = (0, react_1.css)(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n    display: flex;\n    justify-content: flex-end;\n    font-family:'regular';\n    font-size: 20px;\n    p { \n        padding: 0 5px;\n        color: ", "\n    }\n"], ["\n    display: flex;\n    justify-content: flex-end;\n    font-family:'regular';\n    font-size: 20px;\n    p { \n        padding: 0 5px;\n        color: ", "\n    }\n"])), colors_1.colors.fifth);
exports.notDepositStyle = (0, react_1.css)(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n    display: flex;\n    justify-content: flex-end;\n    font-family:'regular';\n    font-size: 20px;\n    p { \n        padding: 0 5px;\n        color: ", "\n    }\n"], ["\n    display: flex;\n    justify-content: flex-end;\n    font-family:'regular';\n    font-size: 20px;\n    p { \n        padding: 0 5px;\n        color: ", "\n    }\n"])), colors_1.colors.customRed);
exports.balanceStyle = (0, react_1.css)(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n    display: flex;\n    justify-content: flex-end;\n    font-family:'regular';\n    font-size: 16px;\n\n    p { \n        padding: 0 5px;\n    }\n    \n"], ["\n    display: flex;\n    justify-content: flex-end;\n    font-family:'regular';\n    font-size: 16px;\n\n    p { \n        padding: 0 5px;\n    }\n    \n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10;
