"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.nButtonStyle = exports.buttonLayoutStyle = exports.settleListLayoutStyle = exports.allRefreshLayoutStyle = exports.allButtonStyle = exports.refresh = exports.time = exports.balance = exports.place = exports.textLayoutStyle = exports.layoutStyle = void 0;
var react_1 = require("@emotion/react");
var colors_1 = require("@/styles/colors");
exports.layoutStyle = (0, react_1.css)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    width:100%;\n    display:flex;\n    flex-direction: column;\n"], ["\n    width:100%;\n    display:flex;\n    flex-direction: column;\n"])));
exports.textLayoutStyle = (0, react_1.css)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    display:flex;\n    flex-direction:column;\n    gap:15px;\n    margin-bottom:15px;\n    padding: 0 30px;\n"], ["\n    display:flex;\n    flex-direction:column;\n    gap:15px;\n    margin-bottom:15px;\n    padding: 0 30px;\n"])));
exports.place = (0, react_1.css)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    font-family: 'semibold';\n    font-size:24px;\n"], ["\n    font-family: 'semibold';\n    font-size:24px;\n"])));
exports.balance = (0, react_1.css)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    font-family:'semibold';\n    font-size:18px;\n"], ["\n    font-family:'semibold';\n    font-size:18px;\n"])));
exports.time = (0, react_1.css)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["\n    font-family: 'regular';\n    font-size: 16px;\n"], ["\n    font-family: 'regular';\n    font-size: 16px;\n"])));
exports.refresh = (0, react_1.css)(templateObject_6 || (templateObject_6 = __makeTemplateObject(["\n    font-family:'semibold';\n    font-size: 14px; \n    display: flex;\n    flex-direction: row;\n    align-items: center;\n    justify-content: flex-end;\n    img {\n        width:24px;\n        height:24px;\n    }\n    \n"], ["\n    font-family:'semibold';\n    font-size: 14px; \n    display: flex;\n    flex-direction: row;\n    align-items: center;\n    justify-content: flex-end;\n    img {\n        width:24px;\n        height:24px;\n    }\n    \n"])));
var allButtonStyle = function (isAll) { return (0, react_1.css)(templateObject_7 || (templateObject_7 = __makeTemplateObject(["\n    button {\n    height:100%;\n    font-family:'semibold';\n    background-color: ", ";\n    border-radius: 15px;\n    border: solid 2px ", ";\n    color: ", ";\n\n"], ["\n    button {\n    height:100%;\n    font-family:'semibold';\n    background-color: ", ";\n    border-radius: 15px;\n    border: solid 2px ", ";\n    color: ", ";\n\n"])), isAll ? colors_1.colors.white : colors_1.colors.fourth, colors_1.colors.fourth, isAll ? colors_1.colors.fourth : colors_1.colors.white); };
exports.allButtonStyle = allButtonStyle;
exports.allRefreshLayoutStyle = (0, react_1.css)(templateObject_8 || (templateObject_8 = __makeTemplateObject(["\n    display: flex;\n    flex-direction:row;\n    justify-content:space-between;\n\n"], ["\n    display: flex;\n    flex-direction:row;\n    justify-content:space-between;\n\n"])));
exports.settleListLayoutStyle = (0, react_1.css)(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n    /* margin: 10px 0; */\n    width:100%;\n    height: 450px;\n    display:flex;\n    flex-direction: column;\n    overflow-y: auto;\n\n    &::-webkit-scrollbar {\n        display: none; \n    }\n"], ["\n    /* margin: 10px 0; */\n    width:100%;\n    height: 450px;\n    display:flex;\n    flex-direction: column;\n    overflow-y: auto;\n\n    &::-webkit-scrollbar {\n        display: none; \n    }\n"])));
exports.buttonLayoutStyle = (0, react_1.css)(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n    padding-top:10px;\n    width:100%;\n    display:flex;\n    flex-direction: column;\n    justify-content:center;\n    align-items:center;\n"], ["\n    padding-top:10px;\n    width:100%;\n    display:flex;\n    flex-direction: column;\n    justify-content:center;\n    align-items:center;\n"])));
exports.nButtonStyle = (0, react_1.css)(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n    display: flex;\n    flex-direction: row;\n    justify-content: right;\n    align-items: center;\n    gap: 10px;\n    font-family: 'medium';\n    font-size: 20px;\n    color: ", ";\n    padding-right: 20px;\n    padding-top: 10px;\n\n    button {\n        font-family: 'semibold';\n        font-size: 16px;\n        width: 45px;\n        height: 45px;\n        color: ", ";\n        background-color: ", ";\n        border-radius: 50%;\n        border: solid 2px ", ";\n    }\n"], ["\n    display: flex;\n    flex-direction: row;\n    justify-content: right;\n    align-items: center;\n    gap: 10px;\n    font-family: 'medium';\n    font-size: 20px;\n    color: ", ";\n    padding-right: 20px;\n    padding-top: 10px;\n\n    button {\n        font-family: 'semibold';\n        font-size: 16px;\n        width: 45px;\n        height: 45px;\n        color: ", ";\n        background-color: ", ";\n        border-radius: 50%;\n        border: solid 2px ", ";\n    }\n"])), colors_1.colors.third, colors_1.colors.third, colors_1.colors.white, colors_1.colors.third);
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11;
