spring:
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:~/MoYeoBangApplication
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 100

  data:
    redis:
      host: 127.0.0.1
      port: 6379

moyeobang:
  storage:
    path: ./images

cloud:
  aws:
    credentials:
      accessKey: AKIAVVZON63HMZBYSHXO
      secretKey: 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
    s3:
      bucket: moyeobang-ssafy

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true


---
spring:
  config:
    activate:
      on-profile: test

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never


---
spring:
  config:
    activate:
      on-profile: deploy

  datasource:
    url: jdbc:mysql://j11c102.p.ssafy.io:3306/moyeobang?serverTimezone=UTC&characterEncoding=UTF-8
    username: c102
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: create