"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.twoIconsHeaderStyle = exports.closeButtonHeaderStyle = exports.backButtonHeaderStyle = exports.headerStyle = void 0;
var react_1 = require("@emotion/react");
exports.headerStyle = (0, react_1.css)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n  position: fixed;\n  top: 0;\n  left: 50%; /* \uAC00\uB85C \uC911\uC559\uC73C\uB85C \uC124\uC815 */\n  transform: translateX(-50%); /* \uAC00\uB85C \uC911\uC559\uC73C\uB85C \uC774\uB3D9 */\n  display: flex;\n  align-items: center;\n  justify-content: space-between; /* \uC544\uC774\uCF58 \uC0AC\uC774\uC5D0 \uACF5\uAC04\uC744 \uCD94\uAC00 */\n  max-width: 390px;\n  width: 100%; /* \uC804\uCCB4 \uB108\uBE44\uC5D0 \uB9DE\uAC8C */\n  height: 50px;\n  padding: 0 10px;\n  z-index: 2;\n  box-sizing: border-box;\n  background-color: transparent; /* \uBC30\uACBD\uC744 \uD22C\uBA85\uC73C\uB85C */\n"], ["\n  position: fixed;\n  top: 0;\n  left: 50%; /* \uAC00\uB85C \uC911\uC559\uC73C\uB85C \uC124\uC815 */\n  transform: translateX(-50%); /* \uAC00\uB85C \uC911\uC559\uC73C\uB85C \uC774\uB3D9 */\n  display: flex;\n  align-items: center;\n  justify-content: space-between; /* \uC544\uC774\uCF58 \uC0AC\uC774\uC5D0 \uACF5\uAC04\uC744 \uCD94\uAC00 */\n  max-width: 390px;\n  width: 100%; /* \uC804\uCCB4 \uB108\uBE44\uC5D0 \uB9DE\uAC8C */\n  height: 50px;\n  padding: 0 10px;\n  z-index: 2;\n  box-sizing: border-box;\n  background-color: transparent; /* \uBC30\uACBD\uC744 \uD22C\uBA85\uC73C\uB85C */\n"])));
exports.backButtonHeaderStyle = (0, react_1.css)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n  ", "\n  background-color: white;\n  justify-content: flex-start;\n"], ["\n  ", "\n  background-color: white;\n  justify-content: flex-start;\n"])), exports.headerStyle);
exports.closeButtonHeaderStyle = (0, react_1.css)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n  ", "\n  background-color: white;\n  justify-content: flex-end;\n  z-index: 2;\n"], ["\n  ", "\n  background-color: white;\n  justify-content: flex-end;\n  z-index: 2;\n"])), exports.headerStyle);
exports.twoIconsHeaderStyle = (0, react_1.css)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n  ", "\n  background-color: transparent;\n  justify-content: flex-end;\n  z-index: 2;\n"], ["\n  ", "\n  background-color: transparent;\n  justify-content: flex-end;\n  z-index: 2;\n"])), exports.headerStyle);
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
